[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kernel"
test = false
bench = false

[dependencies]
bootloader_api = "0.11"
noto-sans-mono-bitmap = { version = "0.3", default-features = false, features = [
    "regular", "size_16", "unicode-basic-latin",
] }
spin = "0.12"
uart_16550 = "0.7"
x86_64 = "0.15"
